// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSR_Automation.Data.DBConnection;

namespace PSR_Automation.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20211120134558_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("PSR_Automation.Data.Model.AllSubmission", b =>
                {
                    b.Property<int>("EvaluatioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDivision")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessDivisionLevel2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClarityCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriticalityQuestions")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataContentSolution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataOperationsContact")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataSteward")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutiveSponsor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Forum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ForumDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PSRChecklistQuestions")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SolutionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EvaluatioId");

                    b.ToTable("AllSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
